title: Nates blog
description: Nathan Woloshyn is an undergraduate studying mathematis & computer science at the university of victoria
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist