title: Nates blog
description: Nathan Woloshyn is an undergraduate studying mathematics & computer science at the university of victoria, with a focus on machine learning.
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist